name: 'Team Reviewers Labels Action'
description: 'TODO'
inputs:
  # teams:
  #   description: 'The teams!'
  #   required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'