name: Add labels for team reviewers
description: Checks requested reviewers, takes teams and creates labels for them.
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
