name: Add labels for team reviewers

on: 
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - synchronize
      - updated

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Add labels for team reviewers
    steps:
      - name: Add labels
        uses: productboardlabs/team-reviews-github-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
